#!/bin/sh
#
# This script installs the j-dump2csv to $HOME/opt folder
# and the startup script is being installed to $HOME/bin
#
# This should be compatible with most Linux, CygWin, and MinGW configrations
#
version="x.x.x" # version placeholder
install_path="${HOME}/opt"
run_path="${HOME}/bin"
app="j-dump2csv"
full_app_path="${install_path}/${app}-${version}"

echo "Installing ${app}, version: ${version}"
echo "The installation path: '"${full_app_path}"'"
echo "'"${app}"' command will be placed into '"${run_path}"'"' (make sure it is in $PATH)'

[ ! -d ${full_app_path} ] && ! mkdir -p ${full_app_path} && \
         (echo "Consider creating: '"${full_app_path}"' manually, and re-run install." && exit 1)

[ ! -d ${run_path} ] && ! mkdir -p ${run_path} && \
         (echo "Consider creating: '"${run_path}"' manually, and re-run install." && exit 1)

if [ -w ${install_path} ]
then
    cp -r bin/ ${full_app_path}/
    cp -r lib/ ${full_app_path}/
    cp -r docs/ ${full_app_path}/
    cp -r samples/ ${full_app_path}/
    cp -r vagrant_mysql/ ${full_app_path}/
    echo "${full_app_path}/bin/${app} "'"''$@''"' > ${run_path}/${app}
    chmod ugo+x ${run_path}/${app}
else
    echo "need permission to write to '""${install_path}""', conisder using: 'sudo sh ./install.sh'"
fi
